#!/bin/sh
#
# Start ONVIF service and ONVIF discovery service
#

case "$1" in
  start)
 	echo -n "Starting micropython based ONVIF server and ONVIF discovery server: "
        /usr/bin/micropython /app/onvif.py > /dev/null 2>&1 &
        /usr/bin/micropython /app/onvif_discover.py > /dev/null 2>&1 &

	[ $? == 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	echo -n "Stopping micropython: "
	killall micropython
	[ $? == 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?